const LIMINAL_MAX_SCALE = 1.5;
const LIMINAL_MIN_OPACITY = 0.5;
const THRESHOLD_FACTOR = 0.66;
const PINCH_THRESHOLD = 1;

export {
  LIMINAL_MAX_SCALE,
  LIMINAL_MIN_OPACITY,
  THRESHOLD_FACTOR,
  PINCH_THRESHOLD
}